ARG NGINX_IMAGE=nginx1.23.3
ARG NODE_IMAGE=node16.14.2

FROM 515238770301.dkr.ecr.us-east-1.amazonaws.com/tween:${NODE_IMAGE} AS build

WORKDIR /frontend

RUN apt-get update \
    # install dependencies for cypress
    && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

COPY ./frontend/package.json /frontend/

RUN npm install -g npm@9.1.1 \
    && npm install

COPY --chown=1000:1000 ./frontend/ /frontend/

RUN npm run build


FROM 515238770301.dkr.ecr.us-east-1.amazonaws.com/tween:${NGINX_IMAGE}

RUN mkdir /etc/nginx/sites-available \
    && mkdir /etc/nginx/sites-enabled \
    && mkdir /usr/share/nginx/html/build \
    && rm /usr/share/nginx/html/index.html

COPY --from=build /frontend/build/ /usr/share/nginx/html/build/

COPY ./utils/nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./utils/nginx/my_nginx.conf /etc/nginx/sites-available/

RUN ln -s /etc/nginx/sites-available/my_nginx.conf /etc/nginx/sites-enabled/

